eveseat/eveapi

- src/Models/Character/ContactList.php
- src/Models/Character/ContactListAlliance.php
- src/Models/Character/ContactListAllianceLabel.php
- src/Models/Character/ContactListCorporate.php
- src/Models/Character/ContactListCorporateLabel.php
- src/Models/Character/ContactListLabel.php
This models modification will fix the issue #5 related to wrong labels display on contact.
> Provide a fix to eveseat/seat issue #5

- src/Api/Corporation/Shareholders.php
The issue was caused by a wrong variable name.
(thanks qu1ckkkk)
Fix issue https://github.com/eveseat/seat/issues/21
> Provide a fix to eveseat/seat issue #21

- src/database/migrations/2016_10_19_153505_fix_strictmode_timestamp_columns.php
ensure long term validity by removing it from current environment
> fix migration by removing zero date from executing modes

- src/Api/Character/AssetList.php
- src/Models/Character/AssetList.php
- src/Models/Character/AssetListContents.php
- src/database/migrations/2017_01_02_190132_update_character_assets_for_nesting.php
> Character Assets are now pulled recursively

- src/Api/Character/NotificationTexts.php
```
Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '626285838' for key 'PRIMARY' (SQL: insert into `character_notifications_texts` (`notificationID`, `text`, `updated_at`, `created_at`) values (626285838, aggressorAllianceID: 1042504553
aggressorCorpID: 98474987
aggressorID: 95467081
planetID: 40127234
planetTypeID: 11
reinforceExitTime: 131367710590000000
solarSystemID: 30001993
typeID: 2233
, 2017-04-14 10:02:54, 2017-04-14 10:02:54)) in /srv/dae-i.eveseat.net/vendor/laravel/framework/src/Illuminate/Database/Connection.php:770
Stack trace:
#0 /srv/dae-i.eveseat.net/vendor/laravel/framework/src/Illuminate/Database/Connection.php(726): Illuminate\Database\Connection->runQueryCallback('insert into `ch...', Array, …
```
> avoid duplicate entry on character notification update

- src/Models/Eve/ApiKey.php
- src/database/migrations/2017_09_20_232400_delete_outdated_people_group.php
clean database of existing corrupted records
> provide hotfix for people & group when a key is deleted

- src/Api/Character/Clones.php
re-created PR against 2.x branch
> fix duplicate entry erro while inserting jump clones

- src/Jobs/Corporation/AllianceHistory.php
- src/Jobs/Corporation/Blueprints.php
- src/Jobs/Corporation/Facilities.php
- src/Jobs/Corporation/Info.php
- src/Jobs/Corporation/MemberTracking.php
- src/Jobs/Corporation/Members.php
- src/Jobs/Corporation/Shareholders.php
- src/Jobs/Corporation/Standings.php
- src/Models/Corporation/CorporationAllianceHistory.php
- src/Models/Corporation/CorporationBlueprint.php
- src/Models/Corporation/CorporationFacility.php
- src/Models/Corporation/CorporationInfo.php
- src/Models/Corporation/CorporationMember.php
- src/Models/Corporation/CorporationMemberTracking.php
- src/Models/Corporation/CorporationShareholder.php
- src/Models/Corporation/CorporationStanding.php
- src/database/migrations/2018_01_16_203100_create_corporation_alliance_histories_table.php
- src/database/migrations/2018_01_16_203100_create_corporation_blueprints_table.php
- src/database/migrations/2018_01_16_203100_create_corporation_facilities_table.php
- src/database/migrations/2018_01_16_203100_create_corporation_infos_table.php
- src/database/migrations/2018_01_16_203100_create_corporation_member_trackings_table.php
- src/database/migrations/2018_01_16_203100_create_corporation_members_table.php
- src/database/migrations/2018_01_16_203100_create_corporation_shareholders_table.php
- src/database/migrations/2018_01_16_203100_create_corporation_standings_table.php
- facilities
- standings (npc)
- blueprint
- members
- member tracking
- alliance history
- info
- shareholders
> Provide support for some root level corporation endpoints

- src/Jobs/Corporation/MembersLimit.php
- src/Jobs/Corporation/OutpostDetails.php
- src/Jobs/Wallet/Corporation/Balances.php
- src/Jobs/Wallet/Corporation/Journals.php
- src/Jobs/Wallet/Corporation/Transactions.php
- src/Models/Corporation/CorporationMembersLimit.php
- src/Models/Wallet/CorporationWalletBalance.php
- src/Models/Wallet/CorporationWalletJournal.php
- src/Models/Wallet/CorporationWalletJournalExtraInfo.php
- src/Models/Wallet/CorporationWalletTransaction.php
- src/database/migrations/2018_01_18_203000_create_corporation_members_limit_table.php
- src/database/migrations/2018_01_19_213039_create_corporation_wallet_balances_table.php
- src/database/migrations/2018_01_19_213044_create_corporation_wallet_journals_table.php
- src/database/migrations/2018_01_19_213110_create_corporation_wallet_journal_extra_infos_table.php
- src/database/migrations/2018_01_19_213119_create_corporation_wallet_transactions_table.php
this one is closing `Corporation` tags
> add the missing corporation limit endpoint

- src/Jobs/Alliances/Alliances.php
- src/Jobs/Alliances/Info.php
- src/Jobs/Alliances/Members.php
- src/Models/Alliances/Alliance.php
- src/Models/Alliances/AllianceMember.php
- src/database/migrations/2018_01_21_130409_create_alliances_table.php
- src/database/migrations/2018_01_21_142417_create_alliance_members_table.php
I had to alter that line in order to make jobs work https://github.com/eveseat/eveapi/blob/master/src/Jobs/EsiBase.php#L196
from `return $this->client;` to `return $this->client->get();`
But, I didn't put it inside the PR since I must admit that I don't get all about this method
> implement alliance endpoints

- src/Models/Character/CharacterInfo.php
- src/Models/Clones/CharacterImplant.php
- src/Models/Clones/CharacterJumpClone.php
- src/Models/Sde/InvType.php
- src/Models/Sde/StaStation.php
- src/Models/Skills/CharacterSkillQueue.php
Add the SDE model with read-only support
Connect character models together in order to make the view building easier
depends on eveseat/web#98
> add few model relation related to character sheet view

- src/Config/eveapi.corp_roles.php
- src/Jobs/Corporation/MembersLimit.php
- src/Jobs/Universe/Stations.php
- src/Models/Corporation/CorporationInfo.php
- src/Models/Corporation/CorporationMemberLimits.php
TODO : review universe jobs and scopes checker
> fix corporation sheet with ESI upgrade

- src/Jobs/Industry/Character/Mining.php
- src/Jobs/Market/Prices.php
- src/Models/Character/CharacterInfo.php
- src/Models/Industry/CharacterMining.php
- src/Models/Market/Price.php
- src/database/migrations/2017_12_01_000000_create_market_prices_table.php
update SDE Model to return price
add price model and jobs to handle universe/market/prices
update character mining job to handle time based ledger
depends on eveseat/web#137
depends on eveseat/console#17
depends on eveseat/services#47
> integrate eveseat-mining-ledger in core

- src/Models/Corporation/CorporationMemberTracking.php
* temp. commented ship-type due to missing location.
> Enabler: Include Main Character to MemberTracking

- src/Jobs/Universe/Structures.php
- src/Traits/PerformsPreFlightChecking.php
- src/database/migrations/2018_08_30_211652_purge_universe_structure_issue436.php
Redesign queries which are returning structure_id with help of @GoldenGnu
https://docs.esi.evetech.net/docs/asset_location_id
Closes eveseat/seat#436
> fix(structure resolver): Improve queries returning structure_id

- src/Models/Sde/MapDenormalize.php
> fix(sde): Remove typeID special attribute as it is already defined

- src/Jobs/Character/Notifications.php
- src/Jobs/Market/Corporation/Orders.php
- src/database/migrations/2018_11_27_214358_update_corporation_orders_to_v3.php
This pull request is taking care of Jobs based on long time outdated endpoint which will be removed in next ESI Iteration (between now and end of the year).
https://github.com/esi/esi-issues/blob/master/changelog.md#2018-07-08 corporation order v2 depreciation
https://github.com/esi/esi-issues/blob/master/changelog.md#2018-09-14 character notification v2 depreciation
https://github.com/esi/esi-issues/blob/master/changelog.md#2018-12-11 character notification v3 depreciation (will be handled as soon as it will be released).
> Outdated endpoints

- src/EveapiServiceProvider.php
Referring to the documentation https://laravel.com/docs/5.5/packages#migrations
> Load migrations from

- src/Models/Killmails/CharacterKillmail.php
- src/Models/Killmails/KillmailDetail.php
- src/Models/Killmails/KillmailVictim.php
Using relations instead of joins.
This PR takes use of relations to universeNames -> https://github.com/eveseat/web/pull/236
> 459 character killmail

- src/Jobs/Industry/Corporation/Mining/ObserverDetails.php
- src/Models/Industry/CorporationIndustryMiningObserverData.php
- src/database/migrations/2018_12_09_110558_fix_corporation_industry_mining_observer_data_primary_keys.php
Observer mining data needs to have last_updated as a primary key or the data does not copy to the database correctly
> Observer mining data needs last_updated as a primary key

- src/Models/Corporation/CorporationStructure.php
- src/Models/Industry/CorporationIndustryMiningExtraction.php
- src/Models/Sde/MapDenormalize.php
- src/Models/Universe/UniverseMoonContent.php
- src/database/migrations/2018_12_29_184657_create_moon_content_table.php
Improve models relationship in order to provide data for moon-mining extraction UI.
> Corp extractions

- src/Jobs/Location/Character/Location.php
- src/Models/Location/CharacterLocation.php
- src/database/migrations/2019_03_05_182404_add_solar_id_to_character_locations.php
resolves: https://github.com/eveseat/seat/issues/540
> Add solar_system_id to character_locations table and use in summary

- src/Config/eveapi.config.php
- src/Helpers/EseyeSetup.php
parameters from .env is only read at boot stage - then, configuration
files are used.
https://github.com/laravel/framework/issues/21727
> fix(config): put environment variables into config file

- src/Models/Corporation/CorporationInfo.php
My bad. I don't have a working Intellisense.
> fix(relationship): fix a reference error

- src/Jobs/AbstractCorporationJob.php
remove the job funnel introduced with eveseat/eveapi#135
> revert(jobs): reduce duplicated jobs

- src/Models/Corporation/CorporationTitle.php
- src/database/migrations/2019_08_06_213858_remove_corporation_title_surrogate_key.php
use an unique index instead primary key to maintain integrity.
> refactor(titles): remove surrogate key by standard auto-increment key

- src/database/migrations/2019_08_24_193243_remove_character_bookmark_folders_surrogate_key.php
- src/database/migrations/2019_08_24_234635_remove_corporation_bookmarks_surrogate_key.php
- src/database/migrations/2019_08_24_234651_remove_corporation_bookmark_folders_surrogate_key.php
remove index creation on both character and corporation fields since it already exists.
> fix(bookmarks): remove entity index creation which already exists

- composer.json
- src/Jobs/Bookmarks/Character/Folders.php
- src/Jobs/Contacts/Character/Labels.php
- src/Jobs/Contacts/Corporation/Labels.php
- src/Jobs/Fittings/Character/Fittings.php
- src/Jobs/Fittings/Insurances.php
- src/Models/Character/CharacterNotification.php
- src/Models/Corporation/CorporationMemberTracking.php
- src/Models/Corporation/CorporationStarbase.php
- src/Models/Industry/CharacterMining.php
- src/Models/Mail/MailHeader.php
- src/Models/Sde/InvType.php
- src/Traits/RateLimitsEsiCalls.php
- src/database/migrations/2019_08_24_193243_remove_character_bookmark_folders_surrogate_key.php
- src/database/migrations/2019_08_24_234635_remove_corporation_bookmarks_surrogate_key.php
- src/database/migrations/2019_08_24_234651_remove_corporation_bookmark_folders_surrogate_key.php
- src/database/migrations/2019_10_15_172737_add_timestamps_to_insurances_table.php
This pull request is including the following changes targeting 4th generation :
- upgrade framework from Laravel 5.5 to new Laravel 6
- replace redis middleware with php-redis extension
- query optimization
- default relationship when no candidates can be found
> Starting work on SeAT 4.x

- src/Jobs/Assets/Character/Assets.php
- src/Jobs/Character/Affiliation.php
- src/Jobs/EsiBase.php
- src/Jobs/Skills/Character/Skills.php
- src/Models/Character/CharacterInfo.php
- src/Models/RefreshToken.php
refactor jobs flow for affiliations, assets and skills in order to ensure squads event will be triggered
> Feat squads

- composer.json
- src/Exception/EsiDownException.php
- src/Exception/EveServerDownException.php
- src/Jobs/EsiBase.php
- src/Jobs/Middleware/CheckEsiStatus.php
- src/Jobs/Middleware/CheckServerStatus.php
- src/Jobs/Universe/Structures.php
- src/Models/Universe/UniverseName.php
- src/database/migrations/2020_01_11_182526_add_index_on_from_in_mail_headers_table.php
- src/database/migrations/2020_01_11_182830_add_index_on_corporation_id_in_character_affiliations.php
- src/database/migrations/2020_01_11_182930_add_index_on_alliance_id_in_character_affiliations.php
- src/database/migrations/2020_01_11_183001_add_index_on_faction_id_in_character_affiliations.php
This pull request implement a few new things related to ESI job flow.
It introduce some middlewares and catch errors to better manage jobs when servers are down.
Also provide some fix regarding Intel Mail Stats.
> Improve ESI Job flow

- src/Jobs/Assets/Character/Assets.php
- src/Jobs/Assets/Corporation/Assets.php
- src/database/migrations/2020_02_09_192020_update_character_assets_v4.php
- src/database/migrations/2020_02_09_192020_update_corporation_assets_v4.php
https://github.com/esi/esi-issues/blob/master/changelog.md#2020-01-23
> feat(assets): bump endpoints to v4 according to ESI changes

- src/Jobs/Universe/Names.php
Solves an issue with PDO error "too many placeholders" when dealing with a large number of objects in the UniverseNames table. Added in the client ID from the transactions table as well for data for us to populate.
> Refactor UniverseNames to break up the query for existing entity id's.

- src/Models/Character/CharacterInfo.php
Updated to hasOneThrough relationship using the refresh token.
> fix(model) fix relation from CharacterInfo to user

- src/Models/Sde/MapDenormalize.php
in order to make query easier to build, this is adding different scopes - entity kind related - to the SDE model.
> feat: add scopes to map model

- src/Jobs/Location/Character/Location.php
/v1/characters/{character_id}/location is pending removal (legacy endpoint). Bump to current v2 endpoint. No changes to data returned per Swagger spec.
> feat(esi): bump character location endpoint

- src/Jobs/Killmails/Detail.php
- src/Models/Killmails/Killmail.php
- src/Models/Killmails/KillmailVictim.php
- src/database/migrations/2020_06_09_202647_drop_id_column_into_killmail_victim_items_table.php
- src/database/migrations/2020_06_09_202846_add_flag_to_unique_index_into_killmail_victim_items_table.php
> fix(killmail): switch killmail items to nested relationship and fix job

- src/database/migrations/2019_08_17_212222_remove_character_contacts_surrogate_key.php
- src/database/migrations/2019_08_17_212459_remove_character_contact_labels_surrogate_key.php
- src/database/migrations/2019_08_17_212554_remove_corporation_contacts_surrogate_key.php
- src/database/migrations/2019_08_17_213047_remove_corporation_contact_labels_surrogate_key.php
- src/database/migrations/2019_08_24_192640_remove_character_bookmarks_surrogate_key.php
- src/database/migrations/2019_08_25_090128_remove_corporation_standings_surrogate_key.php
this commit is fixing down parts use to rollback version 3.0.21 changes
> fix(migrations): address issue with rollback process

- src/database/migrations/2019_10_30_131410_drop_character_id_from_mail_headers_table.php
Not sure if this is how you want to handle this, but allows the mig to pass
> fix(mail): add incremental id to mig_mail_recipients

- src/Models/Character/CharacterInfo.php
> refactor(relationships): enforce sort for skills and character corporations history

- src/database/migrations/2020_11_21_103101_remove_unique_key_from_killmail_victim_items_table.php
some cases are not properly handle by the unique index applied on killmail_victim_items table.
for example, you may have two entries related to drones - returned flag will be equal for both - however, they'll contain distinct metadata.
with the new way killmails are processed, this index seems non longer relevant.
```
[
{
"flag": 28,
"item_type_id": 3146,
"quantity_dropped": 1,
"singleton": 0
},
{
"flag": 93,
"item_type_id": 31055,
"quantity_destroyed": 1,
"singleton": 0
},
{
"flag": 16,
"item_type_id": 33101,
"quantity_dropped": 1,
"singleton": 0
},
{
"flag": 27,
"item_type_id": 13003,
"quantity_dropped": 1,
"singleton": 0
},
{
"flag": 22,
"item_type_id": 1952,
"quantity_destroyed": 1,
"singleton": 0
},
{
"flag": 29,
"item_type_id": 12789,
"quantity_dropped": 66,
"singleton": 0
},
{ …
```
> fix: drop unique index on killmail victim items

- src/Models/Fittings/CharacterFitting.php
> fix: prevent invalid ship type to throw an exception

- src/Bus/Alliance.php
- src/Bus/Bus.php
- src/Bus/Character.php
- src/Bus/Corporation.php
- src/Commands/Seat/Buckets/Balance.php
- src/Commands/Seat/Buckets/Info.php
- src/Commands/Seat/Buckets/ListCommand.php
- src/Commands/Seat/Buckets/Update.php
- src/EveapiServiceProvider.php
- src/Models/Bucket.php
- src/Observers/RefreshTokenObserver.php
- src/Traits/BucketManager.php
- src/database/migrations/2020_12_23_200651_create_buckets_table.php
- src/database/migrations/2020_12_23_200711_create_bucket_refresh_token_table.php
- src/database/migrations/2020_12_27_103924_balance_buckets.php
This is related to eveseat/console#88
> refactor: use bucket system to handle tokens update continuously

- src/Models/Corporation/CorporationMemberTracking.php
prevent a null exception to be throw when a character is not in a ship.
> fix(corporation): prevent null exception

- src/database/migrations/2021_03_08_160923_create_title_field_in_character_infos.php
The column use to store the title of a character.
> feat: Create a new column in character_infos called 'title'

- src/Models/Calendar/CharacterCalendarEvent.php
prevent a null exception to be throw when an event detail isn't pulled yet
Closes eveseat/seat#768
> fix(calendar): prevent null exception

- src/Models/Corporation/CorporationStructure.php
> fix: structure fuel use reduction

- src/Jobs/Character/Blueprints.php
- src/Jobs/Corporation/Blueprints.php
> fix: search blueprint by item ID instead of item and owner IDs

- src/Jobs/Corporation/Roles.php
> fix: clean outdated corporation roles non longer returned by ESI

- src/Jobs/Industry/Corporation/Mining/Extractions.php
- src/Models/Industry/CorporationIndustryMiningExtraction.php
- src/Models/Sde/Moon.php
- src/database/migrations/2021_07_29_235411_add_id_column_to_corporation_industry_mining_extractions_table.php
- src/database/migrations/2021_07_29_235411_add_id_column_to_corporation_industry_mining_table.php
This PR allows for multiple extractions to coexist for the same structure. This is important as two extractions may be present at the same time, the currently active asteroid field, as well as the future extraction when the drill is restarted. ESI will only return the latest extraction, so the proposed changes will now take into account the extraction start time when updating extraction data.
> Mining Overhaul

- src/database/migrations/2022_01_04_132020_add_index_ref_type_first_party_id_into_character_wallet_journals_table.php
- src/database/migrations/2022_01_04_132249_add_index_ref_type_second_party_id_into_character_wallet_journals_table.php
add two new indexes to reduce query time for character ratting metrics on dashboard.
ref_type + first_party_id
ref_type + second_party_id
Closes eveseat/seat#853
> feat: improve character wallet journal performances

- src/Jobs/Character/Affiliation.php
- src/Observers/CharacterAffiliationObserver.php
fixes https://github.com/eveseat/seat/issues/879
> Revoke ingame roles when a corporation change is detected

- src/Commands/Eve/Update/Sde.php
fixes https://github.com/eveseat/seat/issues/880
> Update SDE after requiring new tables

- src/Jobs/Corporation/Roles.php
> fix scopes for corporation roles endpoint

- src/Commands/Eve/Update/Sde.php
- src/Jobs/Market/Orders.php
- src/Models/Market/MarketOrder.php
- src/Observers/CharacterAffiliationObserver.php
- src/database/migrations/2023_02_23_174650_add_market_orders_data.php
* this PR ports https://github.com/eveseat/eveapi/pull/339 to seat 5 as discussed on discord
> Market orders for seat 5

- src/Containers/EsiResponse.php
* fix getPagesCount
* getHeader documentation
> fix getPagesCount

- src/Commands/Esi/Update/Prices.php
- src/Jobs/Market/History.php
CCP meant for limit to be 100, meantioned 10 but set tentatively to 300.
> Rate fix - Set to 300

- src/Jobs/Market/Orders.php
- src/Models/Market/MarketOrder.php
- src/database/migrations/2023_05_17_174651_fix_market_orders_data.php
* Fixes the deletion of market orders by adding an updated_at column
> Fix market order deletion

- src/database/migrations/2023_07_01_143956_increase_office_rental_cost_precision.php
I'm currently just looking at my logs to see what fails. Apparently for some station, a 12-digit number is not enough and the job fails. Therefore I increase it with this PR.
Before merging, check the discussion on discord regarding the migration.
> Increase office rental precision

- src/Models/Character/CharacterNotification.php
* adds a cast for https://github.com/eveseat/notifications/pull/83#discussion_r1248867788
> add timestamp cast

- src/database/migrations/2022_01_16_115110_remove_corporation_id_column_from_corporation_title_roles_table.php
A while ago there was a report on discord about a migration failure in `2022_01_16_115110_remove_corporation_id_column_from_corporation_title_roles_table`. This is the discussion surrounding it on discord: https://discord.com/channels/821361165791133716/821361505735278592/1174069308251451392
Basically the issue boils down to the fact that during the migration, a temporarily invalid state can be created that causes a few uniqueness constraints to fail. However, assuming the uniqueness constraint is disabled during the migration, the end result will be valid again. The solution used is to create a temporary column without the uniqueness constraint and then move the values over after the critical step.
For testing and confirming the bug, I create a migration that has to run before …
> fix migration failure from 2022_01_16_115110_remove_corporation_id_column_from_corporation_title_roles_table

- src/database/migrations/2020_11_21_173927_add_unique_on_starbase_id_in_corporation_starbases_table.php
- This fixes the migration issue reported on discord
> fix starbase migration

- src/database/migrations/2022_01_01_171359_add_uuid_to_failed_jobs_table.php
Since we can't figure out what's wrong with tachi's install, just make the migration handle the case.
> improve failed_jobs migration

- src/database/migrations/2022_01_01_171359_add_uuid_to_failed_jobs_table.php
Long story short, while debugging a plugin issue @martinskalicky and I figured out that the [2022_01_01_171359_add_uuid_to_failed_jobs_table.](https://github.com/eveseat/eveapi/blob/5.0.x/src/database/migrations/2022_01_01_171359_add_uuid_to_failed_jobs_table.php#L45-L54) migration sometimes takes excessive time to complete because the process of adding UUIDs with a lot of failed_jobs is very inefficient.
Since `failed_jobs` is very unimportant, instead of migrating it, we just delete all failed jobs.
This also explains the previous failures with this jobs: The user most likely canceled the migration since it took to long, leaving him in a half-migrated state causing the issue with the `uuid` column already existing.
> Fix add_uuid_to_failed_jobs_table once and for all

- src/Commands/Eve/Update/Sde.php
After a session of migration development, I found myself in the situation that SeAT thinks it has the current SDE installed, but the SDE tables don't actually exist. Therefore, the `eve:sde:update` command didn't update the SDE without `--force`
This PR adds a check to ensure the SDE tables exist to the logic deciding whether an SDE update is required.
> import SDE when tables are missing

- src/Jobs/Market/History.php
The `/markets/{region_id}/types/` endpoint has been confirmed to return Type Ids that are not available on the market (or published in the SDE in some cases). This makes the `/markets/{region_id}/history/` calls in this job fail and break the processing of the batch.
Handle this scenario by defaulting to an empty price and continuing.
> Market History: Handle if type is not available on the market

- src/Jobs/Universe/Structures/Citadel.php
- src/Jobs/Universe/Structures/CitadelAccessCache.php
- src/Jobs/Universe/Structures/Citadels.php
- src/Jobs/Universe/Structures/Station.php
- src/Jobs/Universe/Structures/StructureBatch.php
As per the discord discussion, this should improve reliability
> Break up monolith jobs for structure loading

- .gitignore
- src/Config/eseye-cache.php
Changed config for eseye cache to use environment variables so it can be modified more easily
> eseye cache config env

- src/Bus/Character.php
- src/Events/CharacterBatchProcessed.php
This PR is the evapi side of the squad filter performance optimizations.
> Fire event when character batch processed

- src/database/migrations/2024_11_21_150548_reset_select_schedules.php
- src/database/seeders/ScheduleSeeder.php
Continuation of https://github.com/eveseat/seat/issues/731 to also spread global load of contracts and killmails endpoints
> feat: spread esi load for killmails and contracts

- src/Jobs/Middleware/CheckEsiRouteStatus.php
Closes https://github.com/eveseat/seat/issues/915
> fix: check for ivalid route status

- src/database/migrations/2025_01_23_000000_add_index_character_id_date_into_character_wallet_journals_table.php
Closes https://github.com/eveseat/seat/issues/873
> feat: add wallet journal index for charid date

- src/Models/Sde/ChrFaction.php
Ad basic ChrFactions model from SDE
> feat: ChrFactions model

- src/Services/EseyeClient.php
Soft depends on https://github.com/eveseat/eseye/pull/99
Will update PR with composer requirement once eseye release exists.
Closes https://github.com/eveseat/seat/issues/77
> fix: pass contact info to eseye

- src/database/migrations/2025_02_11_000000_remove_deprecated_sso_scopes.php
> fix: remove deprecated sso scopes

- src/Jobs/Killmails/Detail.php
- src/Models/Killmails/KillmailVictim.php
- src/Models/Killmails/KillmailVictimItem.php
Fixes https://github.com/eveseat/seat/issues/924
> fix: don't add killmail victim items multiple times when running jobs concurrently
