src/Api/Eve/CharacterInfo.php
**Issue Background**
`CharacterInfo` will return 3 different datasets depending on an access mask:
* No access mask/API Key provides public info
* Access mask `8388608` provides public info + skill training summary + ship
* Access mask `16777216` provides public info + skill training summary + ship + location + wallet balance
See Docs:
http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/eve/eve_characterinfo.html 
`CharacterInfo` api updates are performed along with all other authenticated API calls. Since `CharacterInfo` is part of the `eve` scope access checks were not being performed against the `char` scope. API keys that did not have `CharacterInfo` access would generate the following EVE API error because authenticated api updates always send a keyID and …
=> CharacterInfo API access mask compatability and legacy deprecation

src/Api/Eve/RefTypes.php
RefTypeNames were not being associated in the journal. It was determined that during EVE API updates the refTypeName was not being populated.
Testing was completed with new RefTypes and existing.
=> Fix for RefTypesModel->refTypeName not updating properly.

src/Api/Character/CharacterSheet.php
Since many worker can work on the same characterID (when multiple keys reference same character),
even if we delete all existing clone for a specific character, a constraint issue can occured.
In order to prevent this, replace the simple create statement by a create or update.
=> avoid jump clone duplication

src/database/migrations/2017_08_04_213800_add__sent_date_index_character_mail_messages_table.php
optimise dashboard query for top mail badge by adding an index on sentDate.
This index will be massively used by the order by instruction.
This is used by eveseat/services#24
=> optimise dashboard query for top mail badge

src/Api/Character/Clones.php
Probably because of multiple API keys for the same character being updated at the same time, an error (randomly) occurs while updating jump clones.
Possible fix for https://github.com/eveseat/seat/issues/220
=> fix duplicate entry error while inserting jump clones

src/Jobs/Universe/Structures.php
perform update only on other location and persist unknown structure only if we don't already have it
fix eveseat/seat#241
=> persist unknown structure only if we don't already have it

src/database/migrations/2018_05_13_232211_fix_corporation_industry_mining_observer_data_table.php
Properly fixes https://github.com/eveseat/seat/issues/291:
(warlof's PR corrected the table name to what it should have be in the Model, however the table name in the actual database was still incorrect).
=> Fix Mining ObserverDetails job

src/Jobs/PlanetaryInteraction/Corporation/CustomsOfficeLocations.php
Of all the things, apparently viewing customs office locations requires the accountant role.
Fixes https://github.com/eveseat/seat/issues/346
=> Fix https://github.com/eveseat/seat/issues/346

src/Models/Clones/CharacterJumpClone.php, src/Models/Sde/StaStation.php
Fix character jump clone model relation to target universe structure instead StaStation when
location_type field has a value of structure.
Closes eveseat/seat#397
=> fix(jump clones): Display name of player structure

src/Models/Corporation/CorporationMemberTracking.php, src/Models/Sde/MapDenormalize.php, src/Models/Sde/StaStation.php
Add missing relation between corporation member tracking to universe structure, station and map
tables.
Provide attributes based on universe structure in order to ensure parity between all three
data source.
Show resolved location name instead location ID and display "Unknown Location" if no match.
Closes eveseat/seat#374
=> fix(corporation tracking): fix last location column

src/Models/Character/CharacterInfo.php
Provide pre-computed skillpoints extracted from character_info_skills table. Used to return both
total_sp and unallocated_sp into the API. Contains up-to date swagger documentation.
Closes eveseat/seat#422
=> feat(character): Add the relation to character_info_skills

src/Models/Industry/CharacterMining.php, src/Models/Sde/InvType.php, src/Models/Sde/InvTypeMaterial.php
Since moon ore is quite recent, provided orders prices average and adjusted are quite wrong. In
order to provide more accurate price, alter the amount formula to be based on materials.
=> feat(mining): use ore materials to compute amount instead itself

src/Models/Industry/CharacterMining.php
Since last update applied for price updating, every retrieved ledger entry is leading to a load
from historical_price table. On ledger display, it's causing big issues.
depends on eveseat/services#65 and eveseat/web#225
=> fix(mining ledger): Fix loading time issue due to prices eager-load

src/Jobs/EsiBase.php
Currently, we're only revoking token which have expire. Sometime, user may have to change their
client app which will result to denied access using the previously recorded tokens.
=> fix(token management): Revoke access_token when it does not match with client

src/EveapiServiceProvider.php
This implement a SeAT specific Provider which have to be inherited by all SeAT package (including plugins) to return proper information and implement auto-discovery into a central place.
**Related to**: eveseat/web#258
**Depends**: eveseat/services#80
=> feat(versions): Implement new version management for EveAPI package

src/Jobs/Industry/Character/Mining.php
with removing of eager-loading ore value in commits: https://github.com/eveseat/web/commit/794edd4e823bcdc4cc0d99dc05e6c11ea9e9c8e0#diff-22011822c62a614039762bc1627bbd3bL55 and https://github.com/eveseat/services/pull/68/files#diff-0a192c3f7ec8a7bcc3181ae3229a931bL55
the prices for already existing mining entries would never be set and
would result in 0 rows. Moving the setting out of the `if($delta_quantity != 0)`
clause sets/gets the historical price for the type on this day.
=> Set Historical Prices for mined ore:

src/Jobs/Character/PublicCorporationHistory.php
this is the 2nd public updater for characters without a refresh_token
=> Introduce public corporation history updater

src/Jobs/Assets/Character/Locations.php, src/Jobs/Assets/Corporation/Locations.php, src/database/migrations/2019_04_13_132114_add_assets_type_entity_index.php
Keeping returned coordinates from assets could help to mitigate structures resolving exception.
> Return locations for a set of item ids, which you can get from corporation assets endpoint. Coordinates for items in hangars or stations are set to (0,0,0)
Also add an index on both `type_id` and `corporation_id` or `character_id` accordingly inside `assets` tables.
This will reduce join time.
=> Keep assets coordinates

src/Helpers/EseyeSetup.php
CCP is working hard to make Tranquility ESI compliant together with
Serenity reborn.
According to CCP Bartender, they're targeting a maximum of 48 hours
delay between Tranquility updates and Serenity updates.
Base ESI would be https://esi.evepc.163.com
and the OAuth path should be https://login.evepc.163.com (according to
actual documentation)
Dependencies eveseat/eseye#47
Closes eveseat/seat#550
=> feat(core): Allow to use alternative SSO and ESI endpoints

src/Jobs/Character/Titles.php, src/Models/Character/CharacterInfo.php, src/Models/Corporation/CorporationTitle.php, src/Pivot/Character/CharacterTitle.php, src/database/migrations/2019_08_09_194320_transform_character_title_into_pivot.php
**BREAKING CHANGE:**
`character_titles` is renamed into `character_info_corporation_title` and switch from an atomic table to a pivot table.
- `character_id` is becoming `character_info_character_id`
- `title_id` is becoming `corporation_title_id`
- timestamps `created_at` and `updated_at`
- `name` field is dropped since it's already available into `corporation_titles`
=> Use Eloquent relationship between character and corporation titles

src/Jobs/EsiBase.php
related to recent changes applied to bookmark endpoints
https://developers.eveonline.com/blog/article/temporary-blackout-of-esi-bookmarks
```
access-control-allow-credentials: true
access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent
access-control-allow-methods: GET,HEAD,OPTIONS
access-control-allow-origin: *
access-control-expose-headers: Content-Type,Warning,ETag,X-Pages
X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
access-control-max-age: 600
allow: GET,HEAD,OPTIONS
cache-control: private
content-length: 2
content-type: application/json; charset=UTF-8
date: Tue, 26 Nov 2019 20:10:03 GMT
etag: "ed2e5773d709f4a0654d954884b08db4e152aeb8a70cb70b54e01bc4"
expires: Tue, 26 Nov 2019 21:10:03 GMT
last-modified: Tue, 26 Nov 2019 20:10:03 GMT …
```
=> fix(esi): paginated endpoint may not return x-pages header

src/Jobs/Skills/Character/Queue.php, src/database/migrations/2020_02_09_182013_add_queues_position_to_skill_queue_table_pk.php
due to the primary key based on character_id and type_id, multiple enqueued level targeting same skill were not kept.
this fix ensure we store both level 1 & 2 from same skill if both are queued.
=> fix: ensure enqueued skills are stored

src/Jobs/EsiBase.php
When refreshing an access token from an SSO v1 refresh token from the SSO v2 endpoints, stores the updated SSO v2 refresh token. Also helps if should CCP decide to enable refresh token rotation in the future.
=> feat(jobs): store updated refresh token returned by SSO when refreshing access tokens

src/Jobs/Character/Affiliation.php, src/Models/RefreshToken.php, src/Observers/CharacterAffiliationObserver.php
- Updates the User model relation on the RefreshToken model to use new foreign key.
- character_id does not exist on MailHeaders model any more.  A better use of this was to update CharacterInfo affiliations so we get the characters updated corporation when they change corps since we no longer get this stored directly on the CharacterInfo model any more so it doesn't get updated.
=> fix for CharacterAffiliation job and User relation on RefreshToken model

src/Models/Corporation/CorporationMemberTracking.php
Related to https://github.com/eveseat/services/pull/120 and https://github.com/eveseat/web/pull/386.
Following the removal of the direct correlation between a Character and a SeAT user, updated the model to use RefreshToken instead (which provides a relation to the User model).
=> Update CorporationMemberTracking model from User to RefreshToken

src/Jobs/EsiBase.php
Fixing message that needed to be prefixed with invalid_grant, added additional message to check for that covers SSO v1 token migration failure with SSO v2 endpoints.
=> fix(jobs): Check for the right invalid_grant error messages to disable the refresh token.

src/Jobs/Universe/CharacterStructures.php, src/Jobs/Universe/CorporationStructures.php
Currently the universe structure update jobs exclude structures that are already populated in the Universe Names table, however since default entries with a name of "Unknown Structure" are inserted by the Character and Corporation structure jobs, names are never updated.
This PR ensures the universe structure jobs form a valid array of structure id's to request (presently it passes an object to Guzzle resulting in a 400 Bad Request), and that subsequent runs are checking for updated structure names.
=> Ensure Universe structures jobs can get updated names, and process structure ids correctly

src/Models/Assets/CharacterAsset.php, src/Models/Assets/CorporationAsset.php, src/Models/Bookmarks/CharacterBookmark.php, src/Models/Bookmarks/CorporationBookmark.php, src/Models/Corporation/CorporationMemberTracking.php, src/Models/Corporation/CorporationStarbase.php, src/Models/Corporation/CorporationStructure.php, src/Models/Industry/CharacterMining.php, src/Models/Industry/CorporationIndustryMiningExtraction.php, src/Models/Killmails/KillmailDetail.php, src/Models/PlanetaryInteraction/CorporationCustomsOffice.php, src/Models/Sde/Constellation.php, src/Models/Sde/Moon.php, src/Models/Sde/Planet.php, src/Models/Sde/Region.php, src/Models/Sde/SolarSystem.php, src/Models/Sde/Star.php, src/Models/Universe/UniverseStation.php, src/Models/Universe/UniverseStructure.php, src/database/migrations/2020_05_23_230655_create_constellations_table.php, src/database/migrations/2020_05_23_230728_create_moons_table.php, src/database/migrations/2020_05_23_230744_create_planets_table.php, src/database/migrations/2020_05_23_230806_create_regions_table.php, src/database/migrations/2020_05_23_230823_create_solar_systems_table.php, src/database/migrations/2020_05_23_230843_create_stars_table.php
eloquent does not like internal relation - and generated query can sometimes lead to error (ie: to be able to sort)
this is splitting the mapDenormalize table into 6 specifics sub-tables (most used) :
- regions
- constellations
- systems
- stars
- planets
- moons
=> feat(sde): explode map into specific entities

src/database/migrations/2020_05_31_110744_add_id_column_to_server_statuses_table.php
This fixes migration conflict with src/database/migrations/2020_05_31_110435_add_id_column_to_esi_statuses_table.php
=> fix: update table name for migration to remove conflict with previous esi_statuses migration

src/Config/esi.php, src/Config/eveapi.config.php, src/EveapiServiceProvider.php, src/Helpers/EseyeSetup.php
Configuration related to ESI will now be available inside `SEAT_PATH/config/esi.php` and a new tag will be available (`seat`) - allowing to publish certain part of the project.
This will avoid to use `php artisan vendor:publish --all` :)
Special thanks to @wfjsw which point me to that workflow.
=> feat: publish esi configuration outside package

src/database/migrations/2020_02_29_004319_remove_corporation_industry_mining_observers_surrogate_key.php
Handles the case where there are multiple mining observer ids with differing corporation ids.
=> fix(migrations): handle duplicate mining observer ids

src/Jobs/AbstractJob.php, src/Jobs/EsiBase.php
increased maximum delay before a job must be considered as zombie (30min to 1 hour).
increase attempt from ESI jobs in case of failure (from 1 to 3)
add a delay between each failed attempt (5 minutes)
=> refactor(jobs): make horizon be more gentle with failed jobs

src/Exception/TokenVersionException.php, src/Jobs/AbstractAuthCorporationJob.php, src/Jobs/Middleware/CheckTokenVersion.php, src/Models/RefreshToken.php, src/database/migrations/2020_11_26_000001_add_version_to_refresh_token.php
This PR contains an update to token handling within seat. Now, only correct version tokens will be used. While older versions will be bounced by the middleware. It also adds a console command to update tokens to the latest version.
This relies upon https://github.com/eveseat/console/pull/80
Closes eveseat/seat#675
=> SSO Token Version Handling

src/Jobs/Killmails/Detail.php, src/Jobs/Middleware/KillmailRateLimit.php
Avoid concurrent requests targetting the same killmail using a throttler middleware allowing one killmail job per second.
=> Improve the way we're processing killmails

src/Exception/InvalidAssetLocation.php, src/Jobs/AbstractAuthCorporationJob.php, src/Jobs/AbstractCharacterJob.php, src/Jobs/AbstractCorporationJob.php, src/Jobs/Assets/Character/Locations.php, src/Jobs/Assets/Corporation/Locations.php, src/Jobs/Middleware/RequireCorporationRole.php
This pull request is offering some extra things to better handle job exception, under certain condition.
When ESI is returning an HTTP 403 with message `Character is not in the corporation` when SeAT is requesting a corporation endpoint, we remove relation between the actually known Corporation and Character inside SeAT.
This change will prevent jobs to be run under the character for an invalid corporation until we got up-to-date information regarding him.
---
In order to improve debugging, when ESI is returning an HTTP 404 with message `Invalid IDs in the request`, we continue to attempt IDs resolving (since we're limited to 1000 IDs per request, and may still have valid ID to resolve). AT then end of flow, a generic error will be returned and detailed ID collection will be available in …
=> Improve jobs exception handling

src/Jobs/AbstractAuthCharacterJob.php, src/Jobs/AbstractAuthCorporationJob.php, src/Jobs/AbstractCorporationJob.php, src/Jobs/Middleware/CorporationThrottler.php, src/Jobs/Middleware/EsiTokenThrottler.php
in order to reduce concurrent jobs related to a refresh token, throttle them by id, allowing one job per 2 seconds.
in order to reduce concurrent jobs related to a corporation, throttle them by id, allowing one job per 2 seconds.
=> feat: reduce concurrent jobs related to same entities

src/EveapiServiceProvider.php, src/Exception/PermanentInvalidTokenException.php, src/Exception/TemporaryEsiOutageException.php, src/Exception/UnavailableEveServersException.php, src/Jobs/AbstractJob.php, src/Jobs/EsiBase.php, src/Listeners/EsiFailedCall.php
This is addressing few design issues with the way Jobs are built and processed.
Remove the unnecessary `throw exception` which was in `failed` method. This is called by worker once a job has been reported as failed and must be use to handle cleanup and report only.
The method has also been split between AbstractJob and EsiBase to handle things related to their "nature".
Since AbstractJob is the really base job class, we only handle telemetry reports here.
EsiBase is used by all ESI jobs - we handle token removal and cache update.
Use a listener to prevent jobs to run excessive calls against ESI.
By default, all ESI jobs can run up to 3 times - when they encounter issue. This is usefull for temporary outage. However, it's non relevant when ESI exclusively tell us that what we're doing is …
=> fix(jobs): better handling esi errors

src/database/migrations/2020_12_27_203329_extend_url_size_from_corporation_infos_table.php
some corporation seems using url field for another thing than website promotion
```json
{
"ceo_id": 2116552965,
"creator_id": 2116552965,
"date_founded": "2020-03-29T08:41:27Z",
"description": "Im going to build a wall and make Mexico pay for it. Its going to be the biggest tallest wall you have ever seen. its going to be HUGE!<br><br>Because it came from CHY-NA<br><br><br>https://images.squarespace-cdn.com/content/v1/5b636d3df2e6b15f497da1a3/1544995181232-YSK4I3IXPHKJI8RKH6K2/ke17ZwdGBToddI8pDm48kFTEgwhRQcX9r3XtU0e50sUUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcW7uEhC96WQdj-SwE5EpM0lAopPba9ZX3O0oeNTVSRxdHAmtcci_6bmVLoSDQq_pb/Trump.jpg?format=750w",
"home_station_id": 60014719,
"member_count": 3,
"name": "The Offices of Donald J. Trump",
"shares": …
```
=> fix(jobs): allow url from corporation infos table to store up to 510 characters

src/Jobs/Contracts/Character/Contracts.php, src/Jobs/Contracts/Corporation/Contracts.php, src/Models/Contracts/ContractDetail.php, src/Models/Universe/UniverseStation.php, src/Models/Universe/UniverseStructure.php, src/database/migrations/2021_02_07_194402_add_start_location_type_to_contract_details_table.php, src/database/migrations/2021_02_07_194957_add_end_location_type_to_contract_details_table.php
**BREAKING CHANGE:** `start_location` and `end_location` from `ContractDetail` are now using `morphTo` and can either return an `UniverseStructure` or a `UniverseStation` object depending on situation.
Closes: eveseat/seat#756
=> fix(contracts): allow locations to be linked to either structure or station

src/Models/PlanetaryInteraction/CorporationCustomsOffice.php
reinforce_exit_start and reinforce_exit_end properties from Customs Offices have been cast from integer to date - which prevent data to be stored into the database.
=> fix(jobs): do not cast start/end reinforcement from pocos

src/Commands/Esi/Update/Alliances.php, src/Commands/Esi/Update/Insurances.php, src/Commands/Esi/Update/Prices.php, src/Commands/Esi/Update/Sovereignty.php, src/Commands/Esi/Update/Stations.php, src/EveapiServiceProvider.php, src/Jobs/Alliances/Alliances.php, src/database/seeds/ScheduleSeeder.php
esi:update:public is becoming to big and it lead to various stability issues on large instances.
refactor this command in more granular ones :
- spawn sovereignty, stations and insurances
- merge prices together with history
- merge alliance and use bus
=> refactor: split public jobs in dedicated commands

src/database/migrations/2020_05_31_110243_add_id_column_to_mail_recipients_table.php
This patch will issue a non-altering, alter table statement if the column addition fails. This statement will allow the migration to pass. It is unclear at this stage why this works.
Closes eveseat/seat#814
=> MariaDB 10.5 Hotfix

src/Commands/Esi/Update/PublicInfo.php, src/Models/Alliances/Alliance.php, src/Models/Alliances/AllianceMember.php
This adds some relations to the Alliance and AllianceMember models. It also extends the public info job to grab the public CorporationInfo from ESI when missing.
=> feat: add relations to alliance and update member corps through public

src/Jobs/EsiBase.php
The key name should not be hardcoded. Because a complete key name contains a prefix, and this prefix is not necessarily `seat`, it depends on the config [0].
As an impact, CheckEsiRateLimit middleware may not work. Since EsiBase::getRateLimitKeyTtl() always returns -2, EsiBase::incrementEsiRateLimit() will always set the cache to 1. Ultimately, CheckEsiRateLimit middleware will not do anything even if the error rate has actually been reached.
[0] `Illuminate\Cache\CacheManager::getPrefix()`
=> fix(jobs): Use Cache facade to get key prefix instead of hardcoded

src/Commands/Esi/Update/PublicInfo.php
This removes the automatic creation of CorporationInfo jobs for missing AllianceMembers due to the increased load this can present.
=> fix: remove automatic alliance member population

src/Commands/Esi/Update/PublicInfo.php, src/Jobs/Maintenance.php
This PR will pull public CorpInfo for all AllianceMembers where the Alliance has at least one member corporation.
The maintenance job will also clean up corporations that have no active tokens, and are not a member of an alliance with active tokens.
=> feat: corporation public info pull and cleanup

src/Jobs/Character/Info.php, src/Mapping/Characters/InfoMapping.php
Only change is the drop of `ancestry_id` from the ESI result. Leaving it in the DB for historical purposes, but it will forever be null from now on.
=> fix: bump character info endpoint to v5

src/Jobs/Assets/Corporation/Assets.php
primary key of corporation_assets table is item_id - there is no reason to search on corporation_id when attempt to determine if an asset already exists or not.
Closes eveseat/seat#860
=> fix: remove corporation from unicity check

src/Jobs/EsiBase.php, src/Jobs/Middleware/CheckEsiRouteStatus.php
This middleware will check the esi status and only allow a request if the route is present, and reporting a status of green or yellow.
=> feat: add middleware to check if ESI route is up

src/Jobs/Maintenance.php
I chose these tables after comparing table data length against table size. 
character_assets = DB size: 80MB | Data Length: 33MB
character_fitting_items = DB size: 77MB | Data Length: 31MB
character_wallet_journals = DB size: 164MB | Data Length: 80MB
character_wallet_transactions = DB size: 54MB | Data Length: 26MB
contract_details = DB size: 85MB | Data Length: 54MB
contract_items = DB size: 56MB | Data Length: 39MB
This is comparing against my database of ~450 active tokens, larger databases likely have a greater difference of DB/DL sizes.
=> Maintenance tables add

src/Jobs/AbstractAuthCorporationJob.php, src/Jobs/AbstractJob.php, src/Jobs/EsiBase.php
According to the [documentation](https://laravel.com/docs/10.x/queues#cleaning-up-after-failed-jobs), `failed` callbacks should receive a `Throwable` and not an `Exception`.
This also caused tinker to fail executing the job, so I decided to fix it.
=> fix type hints to the correct type

src/Jobs/PlanetaryInteraction/Corporation/CustomsOfficeLocations.php, src/Models/Sde/MapDenormalize.php, src/Traits/Utils.php
when POCOs are anchored too close from a moon, their location were resolved to the moon instead of the related planet.
Closes eveseat/seat#811
=> fix(jobs): ensure POCOs location are properly resolved

src/Commands/Esi/Update/Prices.php, src/Jobs/Market/History.php
The market history endpoint is supposed to come back up on next monday. On the Eve Partners Discord, there has been some info about how it will come back that I'm not allowed to share. This PR ensures we comply with the new changes and don't run into any issues. After the endpoint is back up, we should search for a better solution than this implementation, but if we do nothing, we will potentially generate one error for every market tradeable item.
=> Rate limit market history for safety reasons

src/Commands/Esi/Update/Prices.php, src/Jobs/AbstractJob.php, src/Jobs/Market/History.php
* Since the default schedule is once per day and faster doesn't make sense, I increased the timeout to 1 day.
* We now use delay to spread them a bit more efficiently
=> Update market history rate limiting - take 2

src/Jobs/Calendar/Events.php
as per ESI documentation:
> Get 50 event summaries from the calendar. If no from_event ID is given, the resource will return the next 50 chronological event summaries from now. If a from_event ID is specified, it will return the next 50 chronological event summaries from after that event
when `from_event` is provided with `0` - the oldest available event and its next 49 events are returned.
as a result, current implementation is looping infinitely since the returned value is always the oldest.
this update is not documented but might be related to endpoint version bump between v1 and v2
provided changes are using last returned event with highest value as a next page source. also removing the event value manipulation which was subtracting 1 from the returned value since its invalid and …
=> fix: character events consumption

src/Jobs/AbstractAllianceJob.php, src/Jobs/AbstractCharacterJob.php, src/Jobs/AbstractCorporationJob.php, src/Jobs/AbstractJob.php
* Some public jobs like killmails can't be batched, because they are missing the `Batchable` trait. This PR moves batchable from character, corporation and alliance job classes to a common ancestor that also includes the public jobs
=> Refactor batchable trait location

src/Jobs/Character/Notifications.php, src/Jobs/EsiBase.php
Jobs for the eveapi not queued properly. Most Jobs were queue into "public" queue due queue override in constructor of "EsiBase" class.
I have removed this while default queue value is already set for public property $queue. Also Notification jobs now queue into "notifications" queue while they are highly important for pings on discord.
=> Fixes queue handling for eveapi jobs

src/database/migrations/2022_01_16_115110_remove_corporation_id_column_from_corporation_title_roles_table.php
I think this should fix the new migration issue experienced by Kiba. It turns out, there was a second issue I didn't catch. Here is his report:
DB migration was failing due to a problem that was thought to be resolved
https://github.com/eveseat/eveapi/pull/379
seat-docker-front-1      |    INFO  Running migrations.
seat-docker-front-1      |
seat-docker-front-1      |   2018_01_05_112025_add_unique_mail_id_on_mail_headers_table ........ 2ms DONE
seat-docker-front-1      |   2018_01_07_162051_add_unique_fitting_id_on_character_fittings_table  1ms DONE
seat-docker-front-1      |   2020_11_21_173927_add_unique_on_starbase_id_in_corporation_starbases_table  47ms DONE
seat-docker-worker-1     | Horizon started successfully.
seat-docker-front-1      | …
=> Fix migration issue

src/Jobs/Market/History.php
It turns out that the market history job basically stalls in a while true loop when it doesn't have any rate limit budget remaining. This PR adds logic to release market history jobs again when the rate limit budget is used up.
=> decrease cpu load

src/Bus/Alliance.php, src/Bus/Character.php, src/Bus/Corporation.php
Currently, if a single job in the ESI batches fails, all the following batches will fail too.
This PR allows failures in the ESI job batches. Additionally, I removed comments that no longer look to be relevant.
This PR isn't very high-priority and doesn't need an immediate release
=> Don't fail job batches if a single job fails

src/Commands/Esi/Update/Prices.php, src/Jobs/Market/DispatchHistoryJobs.php
It turns out that ESI returns an error on the market history endpoint for all type ids that are not in `/markets/{region_id}/types/`. Currently, we get the type ids from the SDE, which might be outdated.
With this PR, we have a job that fetches all type ids from  `/markets/{region_id}/types/` and then schedules market history jobs for them.
=> schedule type ids for market history from esi

src/Jobs/Killmails/Character/Recent.php, src/Jobs/Killmails/Corporation/Recent.php, src/Jobs/Market/History.php, src/Jobs/Market/Prices.php, src/Jobs/PlanetaryInteraction/Character/Planets.php
The PI Plantes job launches new jobs with the data it has loaded from ESI. Normally, these jobs are added to the current batch. However, when manually scheduling an update over the web ui, jobs aren't launched in a batch.
This PR makes the Planets job handle the case where it isn't running in a batch.
=> PI Planets job: create new batch when job isn't running in a batch

src/Jobs/Assets/Character/Assets.php, src/Jobs/Assets/Corporation/Assets.php
A while ago, someone reported that his asset jobs fail with a  SQL error:
```
[2024-01-24 20:14:41] local.ERROR: SQLSTATE[HY000]: General error: 1390 Prepared statement contains too many placeholders (Connection: mysql, SQL: delete from `corporation_assets` where `corporation_id` = XXXXXXXX and `item_id` not in (...,...,...)) at /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php:822)
```
This can happen if a character has too many assets and the `$known_assets` grows too large so that no SQL statement can be generated anymore: https://github.com/eveseat/eveapi/blob/d569e3e8a753da97707b31f6b31aa036f08a6148/src/Jobs/Assets/Character/Assets.php#L134
The fix is to use `updated_at`: Items that have a outdated updated_at are the items that are no longer returned by …
=> delete assets without list of asset ids

composer.json, src/database/seeders/ScheduleSeeder.php
- This PR improves schedule seeding using the helper introduced here: https://github.com/eveseat/services/pull/179
- This other PR is required before this can be merged
- After the other PR is merged and released, we should bump the minimal services version
=> improve schedule seeding

src/Jobs/EsiBase.php
The Redis:: by default use the 'default' redis connection string. Get the 'cache' connection to have the `ttl` and additional commands work towards the same connection.
=> Fixed rate limit issue

src/database/seeders/ScheduleSeeder.php
While copy-pasting the schedule list when refactoring, `eve:update:status` (not to be confused with `esi:update:status`) got lost. 
This job is responsible for deciding if the ESI servers are online and other calls can be made. When creating a new instance, seat never runs this job and therefore refuses to contact ESI. Existing instances continue to work because the schedule seeder doesn't remove command, it only adds new commands so it still runs fine on them.
=> readd eve:update:status

src/Jobs/Middleware/CheckEsiRateLimit.php, src/Jobs/Universe/Structures/Citadel.php
HTTP 403 is frequent for Citadel jobs which in turn decrease the ESI `X-ESI-Error-Limit-Remain`. Decrease RATE_LIMIT to not starve out other jobs.
=> fix: Adjust RATE_LIMIT for Citadel jobs

src/Jobs/Assets/Character/Assets.php, src/Jobs/Assets/Corporation/Assets.php
Potential fix for https://github.com/eveseat/seat/issues/908
Make a change to the model to reference the `$start` time when updated assets so that an update actually occurs on the asset records (`isDirty() = true`)
=> Update `updated_at` for Assets Jobs

src/Jobs/Assets/Character/Assets.php
When we added the `created_at => start` code, I moved over the Corporation::Assets chunk logic to Character::Assets and apparently that explodes. See that changeset here: https://github.com/eveseat/eveapi/compare/5.0.11...5.0.12
This removes that specific copy while keeping the `created_at => $start` bit.
=> Remove (Revert) the chunk logic found in Corporation:Assets

src/Jobs/Assets/Character/Assets.php
Fixes the error count(): Argument #1 ($value) must be of type Countable|array, stdClass given {"exception":"[object] (TypeError(code: 0): count(): Argument #1 ($value) must be of type Countable|array, stdClass given at /var/www/seat/vendor/softcreatr/jsonpath/src/Filters/SliceFilter.php:17).
When the type of a value passed to the `$overrides` parameter of `AssetMapping::make` is not of type `Closure`, it is treated as a key to be checked on the API response and not a static value. When including data in the asset mapping that doesn't come from the API response, it must be passed as part of a closure to avoid this.
The previous version of this code was effectively doing this:
```
$data = json_decode('{"is_singleton":false,"item_id":1234,"location_flag":"Hangar","location_id":1234,"location_ …
```
=> Fix error in Seat\Eveapi\Jobs\Assets\Character\Assets

src/Jobs/Contracts/Character/Items.php, src/Jobs/Contracts/Corporation/Items.php, src/Jobs/EsiBase.php, src/Jobs/Market/History.php
Since we define a retryUntil method in \Seat\Eveapi\Jobs\AbstractJob, $tries is ignored in all subclasses. This commit removes all usages of it, as the $tries definition doesn't do anything for these jobs.
I'll be testing this for a bit longer and then convert this from a draft to a regular PR.
=> refactor: remove $tries from esi jobs

src/Jobs/Universe/Structures/CitadelAccessCache.php, src/Jobs/Universe/Structures/StructureBatch.php
Currently, we launch one citatel job per citadel and character. This PR decreases this to one job per citadel. If the character can't access the citadel, it is put on the access ban list. After a while, the citadel job will be reattempted by a different character, until either all characters get banned or a character can load the name.
Additionally, the citadel access ban timer has been increased.
=> Only allow one concurrent citadel job

src/Models/Corporation/CorporationStructure.php, src/Models/Fittings/CharacterFitting.php
fixes https://github.com/eveseat/seat/issues/904
before:
```
[Huginn, webby boi]
Power Diagnostic System II x1
Power Diagnostic System II x1
Power Diagnostic System II x1
Damage Control II x1
Multispectrum Shield Hardener II x1
Multispectrum Shield Hardener II x1
Large Shield Extender II x1
Large Shield Extender II x1
50MN Cold-Gas Enduring Microwarpdrive x1
Domination Stasis Webifier x1
Small EMP Smartbomb II x1
650mm Artillery Cannon II x1
650mm Artillery Cannon II x1
650mm Artillery Cannon II x1
650mm Artillery Cannon II x1
Medium Core Defense Field Extender II x1
Medium Core Defense Field Extender II x1
Warrior II x2
Valkyrie II x3
Tremor M x1600
Improved Mindflood Booster x1
```
after:
```
[Huginn, webby boi]
Power Diagnostic System II
Power Diagnostic System II
Power Diagnostic …
```
=> fix fitting exports

src/Commands/Seat/Buckets/Update.php, src/Models/Character/CharacterInfo.php, src/Models/Character/CharacterRole.php, src/Models/RefreshToken.php, src/Models/RefreshTokenSchedule.php, src/database/migrations/2024_07_02_103850_add_last_update_scheduled_field.php, src/database/migrations/2024_07_02_103850_add_refresh_token_schedules_table.php
I'm currently working on making it possible to adjust the esi update interval per character. This PR updates the eveapi side of this project.
This PR is already up to collect some early feedback.
This PR modifies how buckets schedule tokens. This means only the hourly esi updates of endpoints on a 1 hour cache timer are affected.
Each `refresh_token` gets an associated entry in the new `refresh_token_schedules` table. This entry contains the last time jobs for the token have been scheduled (`last_update`), and how often the token should be scheduled (`update_interval`). The buckets logic only dispatches jobs if the configured time(`update_interval`) since the last update has passed.
The system is designed with super-long update intervals in mind(think weeks). It stores the last update in …
=> Granular esi scheduling for characters

src/Bus/Alliance.php, src/Bus/Bus.php, src/Bus/Character.php, src/Bus/Corporation.php
Recently a few people started complaining about jobs getting scheduled if the character doesn't have the scopes for the job. While not very critical, it is probablly not a bad thing to fix it. This PR adds a scope check to the job scheduling logic before scheduling a job.
It is also still possible to manually schedule a job for a character without appropriate scopes, only the regular bucket updates are affected by this.
The PR also includes a little refactor of the Bus class: Mainly, addAuthentificatedJobs and addPublicJobs are now a implementation detail of each bus implementation instead of a abstract method.
=> only schedule job if the token has scopes for the job

src/Commands/Seat/Buckets/Update.php, src/InteractsWithToken.php, src/Jobs/EsiBase.php, src/Jobs/Token/RefreshAccessToken.php, src/Services/EseyeClient.php
This PR builds upon https://github.com/eveseat/eseye/pull/98 and adds a job that can refresh access tokens without making esi calls. This way, for example `publicData` tokens can be kept alive.
This is also intended to be integrated with https://github.com/eveseat/eveapi/pull/409 to allow token hibernation(no esi calls for a extended period of time)
Requirements before merging:
- merge and tag https://github.com/eveseat/eseye/pull/98
- bump the eseye dependency
- merge and tag at the same time as https://github.com/eveseat/services/pull/181 (including bumping eveapi->eseye dependency)
=> add access token refreshing logic

src/Commands/Esi/Job/Dispatch.php
`esi:job:dispatch` allows user to manually schedule a specific job. This is mostly used for debugging. To improve the debugging workflow with this command, it would be useful if any errors appear in the terminal and `dd()` works. This can be achieved by dispatching jobs in a blocking way using the `Job::dispatchSync()` method. This PR addss support for running job with `esi:job:dispatch` in blocking, synchronous mode when the `--sync` flag is specified.
=> Feature: Add option to run job synchrounously in esi:job:dispatch

src/Services/EseyeClient.php
With the UA check in the constructor, new installs would fail with the following error as migrations were unable to run.
```
front-2-1      | 
front-2-1      | In Connection.php line 829:
front-2-1      |
front-2-1      |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'seat2.global_set
front-2-1      |   tings' doesn't exist (Connection: mysql, SQL: select value from global_s  
front-2-1      |   ettings where name = admin_contact limit 1)
front-2-1      |
front-2-1      | 
```
This also means the admin contact email change will apply immediately, so can revert https://github.com/eveseat/web/pull/696 and https://github.com/eveseat/docs/pull/183.
=> fix: update ua in invoke, not constructor

src/Jobs/Universe/Structures/Citadel.php
Another debugging tool. Use-case is for figuring out why some citadels don't load for Kiba. Since citaedl jobs might take a while to appear, being able to monitor job for a particular citadel would be useful.
=> citadels: add structure id to job tags

src/Contracts/CitadelAccessCache.php, src/EveapiServiceProvider.php, src/Jobs/Universe/Structures/Citadel.php, src/Jobs/Universe/Structures/DBCitadelAccessCache.php, src/Jobs/Universe/Structures/StructureBatch.php, src/Models/Universe/CitadelAccessCache.php, src/database/migrations/2025_01_31_210832_add_db_citadel_access_cache.php
This PR adds an (experimental) option to store the citadel access cache in the database instead of redis to reduce load when frequently restarting the stack on large installs.
It can be enabled by setting `CITADEL_ACCESS_CACHE=db` in your .env
The goal is also to eventually remove the limit of 1 character per citadel per hour that potentially prevents loading citadels when only a few characters can access a citadel.
=> new citadel access caching strategy: Store access cache in DB

tests/database/factories/CorporationInfoFactory.php
While fixing https://github.com/eveseat/web/pull/702, I got a failure because the corporation_info factory tried to generate two corporations with the same id, violating a database unique constraint.
=> fix: ensure corporation id from factory is unique

src/Jobs/PlanetaryInteraction/Character/PlanetDetail.php
If multiple characters have different `planet_ids` but share the same `type_id`, this query deletes valid records because it only filters by `character_id` and `type_id` without considering `planet_id`.
This should resolve https://github.com/eveseat/seat/issues/922
The results look promising and align with my expectations, but please let me know if I've overlooked anything or made an error in my reasoning.
=> Fix planet content cleanup.

src/Jobs/Universe/Names.php
Related to [https://github.com/eveseat/notifications/pull/110](https://github.com/eveseat/notifications/pull/110)
Allows querying ESI for a specific list of entity IDs instead of querying for all known unresolved entity IDs. I plan to use this to ensure that the victim and attacker data for a killmail has been loaded before sending kill mail notifications.
=> Allow resolving specific universe names

src/Jobs/Universe/Structures/AbstractCitadelAccessCache.php, src/Jobs/Universe/Structures/CacheCitadelAccessCache.php, src/Jobs/Universe/Structures/DBCitadelAccessCache.php, src/database/migrations/2025_04_15_000000_refactor_db_citadel_access_cache.php
Randomizing citadel access ban durations should hopefully help wibla solve the issue where there are citadel load spikes every 4 weeks. For more details, see the discussion on discord.
This changes requires refactoring how the database citadel access cache works. Before, we stored the time of the last failed attempt. This presents issues when determining if a random timespan has passed. We'd have to generate and store the timespan at the time of job failure so it is not "random" again every time we check. Instead, we now store the time where a next attempt can be made in the DB.
Since `CitadelAccessCache` is an interface, I couldn't add a default method for the randomization. Instead, I've opted to create an intermediary abstract class.
=> Performance: randomize citadel access ban durations

src/Jobs/Market/Orders.php
As it stands, the `issued` and `expiry` column in the `market_orders` table both contain the `expiry` date. This comes from the way `expiry` is calculated: it takes `issued` and adds the length of the order. However, that addition modifies `issued` since they point to the same object. This PR fixes this.
=> Market Orders: Use correct issued dat

src/Bus/Character.php
Corporation ID isn't pulled yet for brand new characters, so the job fails when a new character joins.  This change takes that into account. and fixes https://github.com/eveseat/seat/issues/928
=> Fix Character.php for new characters joining seat
